sudo: false
language: python
python:
  - "3.6"
cache: pip
services:
  - redis-server
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - flake8 momkhulu
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
jobs:
  include:
    - stage: test
      python: "3.6"
      # Clear unused build steps
      services:
        - redis-server
      deploy: []
      after_success: []
    - stage: docker
      python: "3.6"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/momkhulu
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "N2WIcnV+VzbYz75dfnttLqGqarqC1pHwh60uRY17A7p4mppN6kV9n7tJiL9PL8ALwcB6nLO/kST0jZTvCpWsMDBK+/tKXHF56fp+3kQlX7Pl3ZzHSavkCrkRHczoWsw+hM4u8eSd7enfjaFU8M8tl+PWX/R67F2f+n0QOtdQCIKM4oAk9guE7l+rz4UXqZ0G3ZMvqF52smmVPCh4SpWkipXpkFQfI5AjCp07sGSiBA49yaw+1ffZXFiE1Ljyh25xHhDn6L57I3rfhvfMAZiLIPkgJWSpCLurKiNQqFGRidvq8S2xzXDRTSzsJVs9QZN/cmkhaJzuhUWikX3IvonzUCPW24rT/YBuBtauTflhWtTd07a0mJnm5lbpIyFp0XunsP2YKhLMNTYVkRkrPzTX/R47BBEAPKuj0TJlyuyJSgzZr5QqXv1LHth8gh/0KSppB52kkrSYNWbRbdYfXj9NJrN3F0OVtBFKEEyH9tpsLRWUhh3oLmtDHBkoITsMIHoDjTk9J5u7KSGIgrYXobNpUOe0OFh2UWyzg+4haZDsO9WSn+/ELVvlNtIHwh0o7Bwp8gxQvFyB7f0IKMYfpsnvWeYRLXweSBjA/NK7p+zsWhTOLWEwiCCX6PrkCwRYMtS4lr9MaQ0lai7QU9GozJkPpKzjcXAsS1QN8su32w2UayQ="

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --pull --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin # yamllint disable-line
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME" # yamllint disable-line
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
