---
sudo: false
language: python
python:
  - "3.6"
cache: pip
services:
  - redis-server
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
jobs:
  include:
    - stage: test
      python: "3.6"
      addons:
        postgresql: '9.4'
      # Clear unused build steps
      services:
        - redis-server
        - postgresql
      deploy: []
      after_success: []
    - stage: docker
      python: "3.6"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/momkhulu
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "OVlY7F5guWWyzmP6rjIIOlk0VZBWU7l1RfuQx6RyKmhTqEHwht6lg7QRgOM5UxtPMQDxT7hdY7fHLPZkMxh8t3tYVK4qctZ0FHup5jhgkPopZCWwzrvyQ1tverMll5j1S9nq2RKLxBH7l4pJHtiEsSf+sQOMRpE3JeRZz89Q30L9zJQ1HvCdeYyxgkJWCL5mzf56n5m2nNu7zTM1PmwaHpFElIazxW2s02AIXSjCwv+le9cngLoNqSoZtUX1mkxSkXhs7twg2lR9VgDXAd7p7voyixRn/dKFD7UnapbMUKUBxI1HbUzbky7rWlNz2/OqLe/XFzZ5dmihK3+nWti67DUFGdeBDoXZTZoxPUMbCZuezRs7uEi+20K9/TuO3xldYp14peUiUPuAcIYgGi3ygDQOvS2/XJMcht9rju+C4BEIA0CjHC5VMZD/7uXc7xBHFjgbITNMT8OPUyNHUcB9FRrB92Hb+SRGteqY1mRDMEq+KdeHy709S3vG4wQ8SvzzCs4JGzC/vRvxxDKua37JYYdDllnUVC5GWXZqibqxLR47vxHLqJe0QkedW4rTlsehEzDNRW8pANQ6veBfstohixdPQ7NLGWF5jK5IffGzIqRRq8HHRO/BlS+p/NPeEQ7w5TdHVzdisGCM9RH2ZBM/BXtcm2wNtD5QD62YaTdfcdg="   # yamllint disable-line

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --pull --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin # yamllint disable-line
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME" # yamllint disable-line
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
