---
sudo: false
language: python
python:
  - "3.6"
cache: pip
services:
  - redis-server
env:
  - secure: "pT9+m43dGFgcEytO02MGumqVFfer+9WWENnRgVPXnl17jfZQ7TCA8RE8gmcas0tLwwj6VRgxch1aHX0lm861iU41wjt6DUg6vmbdibXgUmhfptEZTjYENZ9C5MFeXo35P23PgoDGUdoSjhXAAYYuH55G8Txg5zxhz0SfrhXmeGh4zZPkoVPGG6Ar64+lH7+7kSMLFh2Qcsxe4z/hOJGp7ZYx/NHUgZve9bY8LOtXv/fpQDAO2EHqgrsNdIq/bxCnWTHj3jleV682xxmm2JPrAflI8o6uHsg+y169FowtXGzLXJY3Vbv3Qc1LrOvv3DQYdKLR6K2hBzuRurVbdWUxL+q/mYR3IUMC0i8LhW4pgU/GoUEfJqN94fqRg5kQ4Iu65ldzqBNlJUGAGlXwY5yj7Vlj0uKsoaG71mN1NJQwKsHxqOp7THHARiIUwW1NIR+Ht94e8twoCdLT4zh3OBrpSvXulp1j+zxHkWG53sLLF7bYCey+gUU+JFR3ZpT1dN4y8ZS24I7YvGb6THinmFvMugH0rJZsE321iw2w+m5Kp/ntIYW+l8P8k0i9uX7BjVej+t/2gtAvxSeI2KLI2yvUht/R+tA29XhlNFzwwZBl08twsFahxAfxInD/sLbqqwSBft7yQsmwtFGhQKgXL0P2C+x0dGWqmOT+AaGsRO9FP6s="   # yamllint disable-line
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov
before_script:
  - psql -U postgres -c "CREATE DATABASE momkhulu;"
script:
  - black --check .
  - isort -c -rc .
  - flake8 .
  - py.test --cov=./
  - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)   # yamllint disable-line
jobs:
  include:
    - stage: test
      python: "3.6"
      addons:
        postgresql: '9.4'
      services:
        - redis-server
        - postgresql
      # Clear unused build steps
      deploy: []
      after_success:
        - codecov
    - stage: docker
      python: "3.6"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/momkhulu
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "scvnAM1hGK4Yr9/wTcB5ys57UKckuL2da6/qzW1h4hBXEzOBBY6LiCWKPyqadabuAWUksEL20huYLTydViGzqcaiL17WrfYnKNwxXIM+0+cDUoFe2ODnBhQmd54KZFMkBsQfb4kSG1+03yVuVrgGYom/Xb9yJ9yvwYrnaVcaUYJBhZD/8Jd1u/oXlkx1WDeU0sngY7q872sfFUOwI0GLzM+EbhGy4gRMn6dTR9ZfwMoD4V2qRPriTyWsC5ntnePT3Owd7kCOf0rRXiUgYHwizy/sQM4xQ69BKRd8zYo+xG/7+kT9sF4MSeRMzQ8iNK4w6rVZ8ff4PFwdJchkS2ZLQs+GWxTE/cbOMwMSx5Gtfc5NzQeWCfcY9KLx5hWuYht/oEeHMVcV62qNZodz6LAXYemk/kZXVWKnVI6mw+grg5RYlrkQWkWsaD0ns8rFphl/m4zIFoffJMo7btj10hKU1RdVhAkGDS90rWnpAk/OkR8RCeBZoYrV8t1hKJsdAV3z7mmbUNXOSPuP7cQwjTJB+lHzQuycuRrJX2qie6q8c9y3MNikUlWS4GQEnTrCjEgF4QinAyx7f0HPnA/fXdmP80RluoBib75J+kkY8Uan+gidJnFmXX8bw0673U7UlUeJxcQhtLKV4Nu/A0ohq7i4LzFUenyCrEykRxTIVb6WaOA="   # yamllint disable-line

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --pull --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin # yamllint disable-line
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME" # yamllint disable-line
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
