sudo: false
language: python
python:
  - "3.6"
cache: pip
services:
  - redis-server
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - flake8 momkhulu
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
