---
sudo: false
language: python
python:
  - "3.6"
cache: pip
services:
  - redis-server
env:
  - secure: "apfZZL+xk22IlmkyYEnCi6J475h/F+ffZ2epFzKq+I5VJUpgrzREX0zuDPRM5OON2mNkQnBWMIV0hFaj0c+lVZ++ZRHfKw70QvuFGb0EDX3fWq1nHakiWAxfeoA/1OooYB0peMS+ZxUBfyjoRSHh4HpqOYsUqQN1BZ61edIR0VAhKmOtiq+VjGahmhoqhTNVny43ka0F8z7BY8IWKaK4pBtjo3mNbBnABSTSqerFW/h37HtAEZhgarWkhwdGy18Jbz/L+0E3VSLanqIjzmHaitCFk5/Knw25Riv5incZtcvGZue/LnnpxSZLcMWwtx3hBz6mYB+Aa4APVQ10SgH3+E4WoB8G4XQZBknyljM0BUT+J8glPO6tF1dm4ID6ZbAVT5eFacyBOOb1IvIxBCT6KG9edNDgUv5m5oljwuFz8fIACQDX93CL+HamZF405SHNuyGTor6huwYr5hrwFvfR2SxXdGc2/D39oL2c283I39y4CZqGqTt2VoY7QS8qHmKLHfQpckHEbbP6ypJ+IeAQ6aJurmz8ebNVMlj2LYXpWZ0gZq54ro0JDLTlcIdcD2zTNwgvfUgm4+w9o4T7Is9/N9gP+GiUUe0ILGyEL1hghOLCba4QlQoA5YNwb8rCB3Ju6Q9V7FFH4z8AGf754qvw3tmgSNZOEO5+BqK91XVdhGo="   # yamllint disable-line
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov
script:
  - black --check .
  - flake8 .
  - py.test --cov=./
jobs:
  include:
    - stage: test
      python: "3.6"
      addons:
        postgresql: '9.4'
      services:
        - redis-server
        - postgresql
      # Clear unused build steps
      deploy: []
      after_success:
        - codecov
    - stage: docker
      python: "3.6"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/momkhulu
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "XRNccZNYtg9UuSjtyyenGRTnkoIlYhVTO7ZzFRBqXj3h4T8AQ1NBUp4xISiC8yMpioR9J7YtrjmttVHhvVlpZmChDye8HGY69jokB5WuH0pyxU8qh+ztumYuf2ZVNv13eBFozZ0Cy7bpXQCFUrcywHY6crlnCTOA796ObBPWezSBxyCjWiJz51i+ZTOrVAaQQPI5fdYzGCre2fwc16x77DXyrfkRURjIOZ0WrdlDCV5CEy3vVt8PxV9I9ZmOK6tevADF8qq53Eh43iVpzgP+kO27rDJQzb+VvtSm/7ed0/StbLHMSlFkovM+3djOXvB+XNJrS/dSG3Ic6tTKjgJi/OSOBb3GT6ezdclOUQG3/c4oJNLb2RAkBdb0469+13JSWPudSJNzbug3hx7U5g8gmDUCZ0JzNsgzqkiHFEK6wyAWf+eHuxBV4FkTkF6aZ41vTaEjn85c7tmxAtffnoVnC8k13p2sSpSvnGH4Sr0k+kM+bONaV6cwccJ0XMgU98wHNqeHNoP/LvqzYtlODWQev3vQyhrMiAB2cN4ydNlSBD5ShSFyOioVY/KlbqKpW21m5bN8rs1o4uBdu1ZMEe55kgoRQ34zV8Q3l2rkxk1iNH2EMhSqyKP8pUjCQmrtF/VUmHf7bEjUJP9PO1p/3PJrZj+9bCRN/2IC563QG8LBlPI="   # yamllint disable-line

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --pull --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin # yamllint disable-line
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME" # yamllint disable-line
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
