sudo: false
language: python
python:
  - "3.6"
cache: pip
services:
  - redis-server
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - flake8 momkhulu
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
