sudo: false
language: python
python:
  - "3.6"
cache: pip
services:
  - redis-server
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - flake8 momkhulu
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
jobs:
  include:
    - stage: test
      python: "3.6"
      # Clear unused build steps
      services:
        - redis-server
      deploy: []
      after_success: []
    - stage: docker
      python: "3.6"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/momkhulu
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "gSuh6cuEzt7JRLIZ0Tf+a+2qVzXZu/TqVxFkPbZLO1hP+GZ/CwUv6zdKRStivnqtIt27HkDX1jSWc/2eDazFWlCWbW3dj627vwZcWPT1w6x/x1sVJDpk7OMpk0YEh4sBKXo1c7Dy2uq6yS432GVYoAGqjgQwPfScS2B1mhYDFtIqsy2eczBa0ylNnf80YYaUKNA3MBIQYGeAjClJ+XZt1f5kh/kbm+Y000PxSSgbNmZ+tRfuX1et6wcdfSKo5EZhl5fSgAVyTLvIa6jCffJOrJx7OfaUUPIJmx0EThJA6udDzZMAxNCQssX9ls5zXsk7klhjMI/kl1b6eLvf+bifAFnbnzdq1W4s7ZZZHvPLibdkI0EdIcU/SeBU9rLfSG9aSQvEXgqy5V48mSYETQCgH7ii9ATOB/QbBNCdhh1M13iGrLdGYSeQGzvANr3gP+l7yTh7fS6PXq8OtcfaWSJsV+lM1wqp/owZPs2OGH2rWhXgn4XLq8qkh4fpVYuXPTNApx6B+f6csU9jQaqFHObtVFrfZySJ+r+aswSNowbGjcNmH6ZHHzvXbgPHfgCHpp0CnCXwXkLBg23dZLSNgXp9ecM4gFxRfZAVsR7SolsvMeubseFsPSeOQ9z1TwVY7H8A1X8SuuiAWRqS3qlOIQG83vEBw9vXUa1j2sOYef5sbiQ="

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --pull --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin # yamllint disable-line
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME" # yamllint disable-line
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
