version: '3'

services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  web:
    restart: always
    build: ./
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: .env
