# Generated by Django 2.0.6 on 2018-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gravidity', models.CharField(max_length=200)),
                ('comorbidity', models.CharField(max_length=200)),
                ('indication', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('urgency', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('clinician', models.CharField(max_length=200)),
            ],
        ),
    ]
