# Generated by Django 2.0.6 on 2018-06-27 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient", name="parity", field=models.IntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="patient", name="time", field=models.TimeField(auto_now_add=True)
        ),
    ]
