# Generated by Django 2.0.6 on 2018-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspatients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('urgency', 'time')},
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
