# Generated by Django 2.0.6 on 2018-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspatients', '0003_auto_20180702_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiententry',
            name='completion_time',
            field=models.DateTimeField(null=True),
        ),
    ]
