# Generated by Django 2.1.7 on 2019-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0006_add_create_update_dates_to_patient_and_entry")]

    operations = [
        migrations.AddField(
            model_name="patiententry",
            name="gravidity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="patiententry",
            name="parity",
            field=models.IntegerField(default=0),
        ),
    ]
