# Generated by Django 2.1.7 on 2019-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0007_add_gravidity_and_parity_to_patiententry")]

    operations = [
        migrations.AddField(
            model_name="patiententry",
            name="baby_weight_grams",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patiententry",
            name="foetus",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patiententry", name="nicu", field=models.BooleanField(null=True)
        ),
    ]
