# Generated by Django 2.1.7 on 2019-05-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0010_add_profile_model")]

    operations = [
        migrations.AlterField(
            model_name="patiententry",
            name="urgency",
            field=models.IntegerField(
                choices=[
                    (1, "Elective"),
                    (2, "Cold"),
                    (3, "Hot"),
                    (4, "Hot"),
                    (5, "Immediate"),
                ],
                default=4,
            ),
        )
    ]
