# Generated by Django 2.1.7 on 2019-06-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0012_remove_baby_fields_from_patiententry")]

    operations = [
        migrations.CreateModel(
            name="Baby",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baby_number", models.IntegerField()),
                ("delivery_time", models.DateTimeField()),
                ("apgar_1", models.IntegerField()),
                ("apgar_5", models.IntegerField()),
                ("baby_weight_grams", models.IntegerField()),
                ("nicu", models.BooleanField()),
                (
                    "patiententry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_babies",
                        to="cspatients.PatientEntry",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="baby", unique_together={("patiententry", "baby_number")}
        ),
    ]
