# Generated by Django 2.1.7 on 2019-06-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0013_add_baby_model")]

    operations = [
        migrations.RemoveField(model_name="patiententry", name="discharge_time")
    ]
