# Generated by Django 2.1.7 on 2019-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0014_remove_patiententry_discharge_time")]

    operations = [
        migrations.AlterField(
            model_name="patiententry",
            name="urgency",
            field=models.IntegerField(
                choices=[
                    (5, "Elective"),
                    (4, "Cold"),
                    (3, "Hot"),
                    (2, "Hot"),
                    (1, "Immediate"),
                ],
                default=4,
            ),
        )
    ]
