# Generated by Django 2.1.7 on 2019-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0015_fix_urgency_choices_on_patient_entry")]

    operations = [
        migrations.AlterField(
            model_name="patiententry",
            name="gravidity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="patiententry",
            name="parity",
            field=models.IntegerField(null=True),
        ),
    ]
