# Generated by Django 2.1.7 on 2019-06-11 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0017_baby_allow_nulls")]

    operations = [
        migrations.AlterField(
            model_name="patiententry",
            name="decision_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
