# Generated by Django 2.2.2 on 2019-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0018_patient_entry_decision_time_default")]

    operations = [
        migrations.AlterField(
            model_name="patient", name="age", field=models.IntegerField(null=True)
        )
    ]
