# Generated by Django 2.2.2 on 2019-06-13 08:36

from django.db import migrations, models


def updatePatientFields(apps, schema_editor):
    PatientEntry = apps.get_model("cspatients", "PatientEntry")
    for entry in PatientEntry.objects.all():
        entry.surname = entry.patient.name
        entry.age = entry.patient.age
        entry.save()


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0019_patient_age_nullable")]

    operations = [
        migrations.AddField(
            model_name="patiententry", name="age", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="patiententry",
            name="surname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(updatePatientFields),
    ]
