# Generated by Django 2.2.2 on 2019-06-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0020_move_patient_fields_to_entry")]

    operations = [
        migrations.RemoveField(model_name="patiententry", name="patient"),
        migrations.AlterField(
            model_name="patiententry",
            name="surname",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(name="Patient"),
    ]
