# Generated by Django 2.2.2 on 2019-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0021_remove_patient_model")]

    operations = [
        migrations.AddField(
            model_name="patiententry",
            name="operation_cancelled",
            field=models.BooleanField(default=False),
        )
    ]
