# Generated by Django 2.1.8 on 2019-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspatients', '0022_patiententry_add_operation_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiententry',
            name='anesthetic_time',
            field=models.DateTimeField(null=True),
        ),
    ]
