# Generated by Django 2.2.2 on 2019-06-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0023_patiententry_anesthetic_time")]

    operations = [
        migrations.AlterField(
            model_name="patiententry",
            name="urgency",
            field=models.IntegerField(
                choices=[
                    (5, "Elective"),
                    (4, "Cold"),
                    (3, "Warm"),
                    (2, "Hot"),
                    (1, "Immediate"),
                ],
                default=4,
            ),
        )
    ]
