# Generated by Django 2.2.2 on 2019-07-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cspatients", "0024_urgency_choices_update")]

    operations = [
        migrations.AddField(
            model_name="patiententry",
            name="starvation_hours",
            field=models.IntegerField(null=True),
        )
    ]
